### ISSUE TITLE
Trouble getting version of flex service running on Internal FlexService Runtime

### ISSUE THREAD

**Issue by kinson** [Kinvey/kinvey-cli#44]
I am currently using the 1.2.1 release of the `kinvey-cli` to manage deployments to an internal FSR but have run into workflow issues because I am unable to retrieve the version of the most recently deployed version of the service from the command line. I was just about to try to implement it myself when I noticed that the very first section of the README actually describes how to get this feature working -- AWESOME! However, when I followed the instructions (running `kinvey recycle`) below `kinvey status` still did not yield the current version of the FSR.

> If you last deployed a Flex service using Kinvey CLI version 1.x you must initiate a one-time recycle (kinvey recycle) before kinvey status will output the service version.

Am I missing a step or is this notice premature (since the only versions released for the cli are 1.X.X)?

Thanks in advance!

**Comment by sjl2024** [comment]
@kinson, thanks for reaching out.

`v1.2.1` definitely doesn't support service version retrieval, but the `v2.0.0` beta does. It was released not long ago and can be installed by running `npm install -g kinvey-cli@next`. Check out the latest README beforehand as you'll need to recycle your current service before the version will be displayed when running `kinvey status`.

You might have seen some of the new README information in the master branch... we use master as our main development branch so the contents don't always match up with what's tagged. In order to be sure, you can always select the latest tag (in the GitHub dropdown) and inspect its contents.

Hope this helps and please reach out if you have any further questions!

Sam

**Comment by kinson** [comment]
Thanks Sam!

I just grabbed the beta version and can now get the service versions 🎉  from the cli!

~ [also] Sam
